<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PD.WiiU.VirtualConsole\PD.WiiU.VirtualConsole.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WiiSharp" Version="0.3.0" />
    <PackageReference Include="WiiUSharp.Nfs" Version="0.6.0" />
  </ItemGroup>

</Project>
