<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PD.WiiU.VirtualConsole\PD.WiiU.VirtualConsole.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets/Frames/*.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WiiUSharp.Audio" Version="0.8.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.0" />
    <PackageReference Include="WiiUSharp.Imaging" Version="0.8.0" />
  </ItemGroup>

</Project>
