<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PD.WiiU.VirtualConsole\PD.WiiU.VirtualConsole.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GMWare.M2" Version="1.1.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\goomba.gba" LogicalName="goomba.gba" />
    <None Include="Assets\GOOMBA.md" />
  </ItemGroup>

</Project>
