<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PD.WiiU.VirtualConsole\PD.WiiU.VirtualConsole.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WiiUSharp" Version="0.9.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Cores\Genesis\genesis_plus_gx_libretro.rpx" LogicalName="cores/genesis_plus_gx_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Genesis\genesis_plus_gx_wide_libretro.rpx" LogicalName="cores/genesis_plus_gx_wide_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Genesis\picodrive_libretro.rpx" LogicalName="cores/picodrive_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\MasterSystem\gearsystem_libretro.rpx" LogicalName="cores/gearsystem_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Atari2600\stella2023_libretro.rpx" LogicalName="cores/stella2023_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Atari7800\prosystem_libretro.rpx" LogicalName="cores/prosystem_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\AtariLynx\handy_libretro.rpx" LogicalName="cores/handy_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\VirtualBoy\mednafen_vb_libretro.rpx" LogicalName="cores/mednafen_vb_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Arcade\fbneo_libretro.rpx" LogicalName="cores/fbneo_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Arcade\mame2003_plus_libretro.rpx" LogicalName="cores/mame2003_plus_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Arcade\mame2010_libretro.rpx" LogicalName="cores/mame2010_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Arcade\mame2000_libretro.rpx" LogicalName="cores/mame2000_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Arcade\mame2003_midway_libretro.rpx" LogicalName="cores/mame2003_midway_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Arcade\fbalpha2012_libretro.rpx" LogicalName="cores/fbalpha2012_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Arcade\fbalpha2012_cps1_libretro.rpx" LogicalName="cores/fbalpha2012_cps1_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Arcade\fbalpha2012_cps2_libretro.rpx" LogicalName="cores/fbalpha2012_cps2_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Arcade\fbalpha2012_cps3_libretro.rpx" LogicalName="cores/fbalpha2012_cps3_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Arcade\fbalpha2012_neogeo_libretro.rpx" LogicalName="cores/fbalpha2012_neogeo_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\PlayStation\pcsx_rearmed_libretro.rpx" LogicalName="cores/pcsx_rearmed_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\PokemonMini\pokemini_libretro.rpx" LogicalName="cores/pokemini_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\NeoGeoPocket\mednafen_ngp_libretro.rpx" LogicalName="cores/mednafen_ngp_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\NeoGeoPocket\race_libretro.rpx" LogicalName="cores/race_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\WonderSwan\mednafen_wswan_libretro.rpx" LogicalName="cores/mednafen_wswan_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Supervision\potator_libretro.rpx" LogicalName="cores/potator_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\GameAndWatch\gw_libretro.rpx" LogicalName="cores/gw_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\ColecoVision\gearcoleco_libretro.rpx" LogicalName="cores/gearcoleco_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Intellivision\freeintv_libretro.rpx" LogicalName="cores/freeintv_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Odyssey2\o2em_libretro.rpx" LogicalName="cores/o2em_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Vectrex\vecx_libretro.rpx" LogicalName="cores/vecx_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\NeoGeoCd\neocd_libretro.rpx" LogicalName="cores/neocd_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Dos\dosbox_pure_libretro.rpx" LogicalName="cores/dosbox_pure_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Commodore64\vice_x64_libretro.rpx" LogicalName="cores/vice_x64_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Commodore128\vice_x128_libretro.rpx" LogicalName="cores/vice_x128_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\AmstradCpc\cap32_libretro.rpx" LogicalName="cores/cap32_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\AmstradCpc\crocods_libretro.rpx" LogicalName="cores/crocods_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\ZxSpectrum\fuse_libretro.rpx" LogicalName="cores/fuse_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\AtariSt\hatari_libretro.rpx" LogicalName="cores/hatari_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Nes\fceumm_libretro.rpx" LogicalName="cores/fceumm_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Nes\nestopia_libretro.rpx" LogicalName="cores/nestopia_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Nes\quicknes_libretro.rpx" LogicalName="cores/quicknes_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Nes\fixnes_libretro.rpx" LogicalName="cores/fixnes_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Snes\snes9x_libretro.rpx" LogicalName="cores/snes9x_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Snes\snes9x2010_libretro.rpx" LogicalName="cores/snes9x2010_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Snes\snes9x2005_plus_libretro.rpx" LogicalName="cores/snes9x2005_plus_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Snes\snes9x2005_libretro.rpx" LogicalName="cores/snes9x2005_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Snes\snes9x2002_libretro.rpx" LogicalName="cores/snes9x2002_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Snes\chimerasnes_libretro.rpx" LogicalName="cores/chimerasnes_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\GameBoy\gambatte_libretro.rpx" LogicalName="cores/gambatte_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\GameBoy\gearboy_libretro.rpx" LogicalName="cores/gearboy_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\GameBoy\fixgb_libretro.rpx" LogicalName="cores/fixgb_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Gba\mgba_libretro.rpx" LogicalName="cores/mgba_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Gba\vbam_libretro.rpx" LogicalName="cores/vbam_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Gba\vba_next_libretro.rpx" LogicalName="cores/vba_next_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Gba\gpsp_libretro.rpx" LogicalName="cores/gpsp_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Tg16\mednafen_pce_libretro.rpx" LogicalName="cores/mednafen_pce_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Tg16\mednafen_pce_fast_libretro.rpx" LogicalName="cores/mednafen_pce_fast_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Tg16\mednafen_supergrafx_libretro.rpx" LogicalName="cores/mednafen_supergrafx_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Msx\bluemsx_libretro.rpx" LogicalName="cores/bluemsx_libretro.rpx" />
    <EmbeddedResource Include="Assets\Cores\Msx\fmsx_libretro.rpx" LogicalName="cores/fmsx_libretro.rpx" />
    <EmbeddedResource Include="Assets\Template\app.xml" LogicalName="template/code/app.xml" />
    <EmbeddedResource Include="Assets\Template\cos.xml" LogicalName="template/code/cos.xml" />
    <EmbeddedResource Include="Assets\Template\meta.xml" LogicalName="template/meta/meta.xml" />
    <EmbeddedResource Include="Assets\Template\iconTex.tga" LogicalName="template/meta/iconTex.tga" />
    <EmbeddedResource Include="Assets\Template\bootTvTex.tga" LogicalName="template/meta/bootTvTex.tga" />
    <EmbeddedResource Include="Assets\Template\bootDrcTex.tga" LogicalName="template/meta/bootDrcTex.tga" />
    <EmbeddedResource Include="Assets\Template\bootLogoTex.tga" LogicalName="template/meta/bootLogoTex.tga" />
    <EmbeddedResource Include="Assets\Template\bootMovie.h264" LogicalName="template/meta/bootMovie.h264" />
    <EmbeddedResource Include="Assets\Template\bootSound.btsnd" LogicalName="template/meta/bootSound.btsnd" />
    <None Include="Assets\CORES.md" />
    <None Include="Assets\TEMPLATE.md" />
  </ItemGroup>

</Project>
